stages:
    - build

variables:
    VLC_UBUNTU_IMAGE: registry.videolan.org/vlc-rs-libvlc-stable-ubuntu:20260728042128
    CARGO_TERM_COLOR: always

build-linux:
    tags:
        - docker
        - amd64
    stage: build
    image: $VLC_UBUNTU_IMAGE
    interruptible: true
    script:
        - cargo test --workspace --all-targets
