stages:
    - build

variables:
    VLC_UBUNTU_IMAGE: registry.videolan.org/vlc-rs-libvlc-stable-ubuntu:20260728042128

vlc-rs-build:
    tags:
        - docker
        - amd64
    stage: build
    image: $VLC_UBUNTU_IMAGE
    script:
        - cargo build --all
